# http://docs.travis-ci.com/user/build-configuration/
# http://docs.travis-ci.com/user/languages/python/

language: python

python:
    - "2.7"
    - "3.2"
    - "3.6"
    - "nightly"
    - "pypy"

install: pip install -r requirements.txt --use-mirrors

script: python setup.py test
